apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  username: dGVzdA==  # base64 encoded 'test'
  password: dGVzdA==  # base64 encoded 'test'
  root-password: cm9vdA==  # base64 encoded 'root'